version: '3.9'

services:
  server:
    container_name: homelab-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - ./packages/server/.env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "
              pnpm --filter ./packages/server exec prisma migrate deploy &&
              pnpm --filter ./packages/server exec prisma generate &&
              pnpm --filter ./packages/server dev
            "

  db:
    image: postgres:16
    restart: unless-stopped
    container_name: homelab-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    container_name: homelab-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: