name: homelab-dev

services:

  migrate:
    container_name: homelab-migrate
    build:
      context: ..
      dockerfile: ./packages/server/docker/Dockerfile.dev
      target: dev
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../packages/shared/.env
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: sh -c "
        pnpm --filter shared exec prisma migrate deploy &&
        pnpm --filter shared exec prisma generate 
      "

  server:
    container_name: homelab-server
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./packages/server/docker/Dockerfile.dev
      target: dev
    ports:
      - "5001:5001"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - ../packages/shared/.env
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
      - server_node_modules:/app/packages/server/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: pnpm --filter server dev

  thumbnail-worker:
    container_name: homelab-thumbnail-worker
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./packages/workers/docker/Dockerfile.thumbnail.dev
      target: dev
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - ../packages/shared/.env
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
      - workers_node_modules:/app/packages/workers/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: pnpm --filter workers dev:thumbnail

  io-workers:
    container_name: homelab-io-workers
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./packages/workers/docker/Dockerfile.io.dev
      target: dev
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - ../packages/shared/.env
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
      - workers_node_modules:/app/packages/workers/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: pnpm --filter workers dev:io

  client:
    container_name: homelab-client
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./packages/client/docker/Dockerfile.dev
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_started
    env_file:
      - ../packages/shared/.env
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
      - shared_node_modules:/app/packages/shared/node_modules
      - client_node_modules:/app/packages/client/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: pnpm --filter client dev

  db:
    image: postgres:16
    container_name: homelab-db
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: homelab-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

  node_modules:
  shared_node_modules:
  server_node_modules:
  workers_node_modules:
  client_node_modules:

  pnpm_store: