export enum CommonErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  MISSING_FIELDS = 'MISSING_FIELDS',
  BAD_REQUEST = 'BAD_REQUEST'
}
