export const enum StorageErrorCode {
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  SERVER_LIMIT_EXCEEDED = 'SERVER_LIMIT_EXCEEDED',
  INVALID_CHUNK_HASH = 'INVALID_CHUNK_HASH',
  INVALID_CHUNK_INDEX = 'INVALID_CHUNK_INDEX',
  UPLOAD_INCOMPLETE = 'UPLOAD_INCOMPLETE',
  UPLOAD_EXPIRED = 'UPLOAD_SESSION_EXPIRED',
  INVALID_OPERATION = 'INVALID_OPERATION',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
}
