export enum AuthErrorCode {
  INVALID_TOKEN = 'AUTH.INVALID_TOKEN',
  TOKEN_REUSED = 'AUTH.TOKEN_REUSED',
  TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  SIGNUP_FAILED = 'AUTH.SIGNUP_FAILED',
  EMAIL_ALREADY_USED = 'AUTH.EMAIL_ALREADY_USED',
  USER_DOES_NOT_EXIST = 'AUTH.USER_DOES_NOT_EXIST',
  INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  OTP_VERIFICATION_REQUIRED = 'AUTH.OTP_VERIFICATION_REQUIRED',
}
