export enum CommonErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  MISSING_FIELDS = 'MISSING_FIELDS',
  BAD_REQUEST = 'BAD_REQUEST',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  NOT_FOUND = 'NOT_FOUND',
  GONE = 'GONE',
}
